name: text-analysis-tool
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - streamlit==1.28.1
    - spacy==3.7.2
    - nltk==3.8.1
    - pandas==2.1.3
    - plotly==5.17.0
